export const Types = {
  GET_DRIVER: "GET_DRIVER",
  UPDATE_DRIVER: "UPDATE_DRIVER",
  GET_DRIVER_VEHICLES: "GET_DRIVER_VEHICLES",
  NEW_DRIVER: "NEW_DRIVER",
  GET_PAYMENT_HISTORY: "GET_PAYMENT_HISTORY",
  UPDATE_PAYMENT_DETAIL: "UPDATE_PAYMENT_DETAIL",
};
