export const Types = {
  GET_VEHICLES: "GET_VEHICLES",
  GET_DISTRICTS: "GET_DISTRICTS",
  GET_AVAILABLE_NETWORKS: "GET_AVAILABLE_NETWORKS",
  CHECK_CUSTOMER: "CHECK_CUSTOMER",
  NEW_PAYMENT: "NEW_PAYMENT",
};
